---
sidebar: sidebar 
permalink: learn/data-protection.html 
keywords: backup, back up, backup apps, back up apps, snapshots, snapshot an app, take a snapshot, take a backup, view backups, view snapshots, set policy, set schedule, schedule backups, schedule snapshots, protect data 
summary: Saiba mais sobre os tipos de proteção de dados disponíveis no Astra Control Service e a melhor forma de usá-los para proteger suas aplicações. 
---
= Proteção de dados
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


[role="lead"]
Saiba mais sobre os tipos de proteção de dados disponíveis no Astra Control Service e a melhor forma de usá-los para proteger suas aplicações.



== Snapshots, backups e políticas de proteção

Os snapshots e os backups protegem os seguintes tipos de dados:

* A aplicação em si
* Volumes de dados persistentes associados à aplicação
* Quaisquer artefactos de recurso pertencentes à aplicação


Um _snapshot_ é uma cópia pontual de um aplicativo que é armazenado no mesmo volume provisionado que o aplicativo. Eles geralmente são rápidos. Você pode usar snapshots locais para restaurar o aplicativo para um ponto anterior no tempo. Os snapshots são úteis para clones rápidos. Os snapshots incluem todos os objetos Kubernetes da aplicação, incluindo arquivos de configuração. Os snapshots são úteis para clonar ou restaurar um aplicativo no mesmo cluster.

Um _backup_ é baseado em um snapshot. Ele é armazenado no armazenamento de objetos externo e, por causa disso, pode ser mais lento de tirar em comparação com snapshots locais. Você pode restaurar um backup de aplicativo para o mesmo cluster ou pode migrar um aplicativo restaurando seu backup para um cluster diferente. Você também pode escolher um período de retenção mais longo para backups. Como eles são armazenados no armazenamento de objetos externo, os backups geralmente oferecem melhor proteção do que os snapshots em casos de falha de servidor ou perda de dados.

Uma _política de proteção_ é uma maneira de proteger um aplicativo criando automaticamente snapshots, backups ou ambos de acordo com uma programação que você define para esse aplicativo. Uma política de proteção também permite escolher quantos snapshots e backups devem ser mantidos na programação e definir diferentes níveis de granularidade do agendamento. Automatizar seus backups e snapshots com uma política de proteção é a melhor maneira de garantir que cada aplicativo seja protegido de acordo com as necessidades de sua organização e requisitos de SLA (Service Level Agreement).


CAUTION: _Você não pode estar totalmente protegido até ter um backup recente_. Isso é importante porque os backups são armazenados em um armazenamento de objetos longe dos volumes persistentes. Se uma falha ou acidente apagar o cluster e seu armazenamento persistente associado, então você precisa de um backup para recuperar. Um instantâneo não permitiria que você se recuperasse.


NOTE: Se você executar um snapshot ou backup, mas a operação falhar com o erro "o recurso não foi criado por causa de um problema de servidor interno", verifique se o back-end de armazenamento que você está usando tem os drivers corretos instalados. Alguns backends de armazenamento precisam de drivers de Container Storage Interface (CSI), enquanto outros precisam de um controlador de snapshot externo.



=== Backups imutáveis

Um backup imutável é um backup que não pode ser alterado ou excluído durante um período especificado. Quando você cria um backup imutável, o Astra Control verifica para garantir que o bucket que você está usando seja um bucket do WORM (write once read many) e, nesse caso, garante que o backup seja imutável a partir do Astra Control. O Astra Control Service dá suporte à criação de backups imutáveis com as seguintes plataformas e tipos de bucket:

* Amazon Web Services usando um bucket do Amazon S3 com o bloqueio de objetos S3 configurado
* Microsoft Azure usando um bucket do Azure com uma política de retenção configurada
* Google Kubernetes Engine (GKE) usando um bucket do Google Cloud Storage com uma política de retenção configurada
* NetApp StorageGRID usando um bucket S3 com bloqueio de objeto S3 configurado


Observe o seguinte ao trabalhar com backups imutáveis:

* Se você fizer backup em um bucket do WORM em uma plataforma não suportada ou em um tipo de bucket não suportado, poderá obter resultados imprevisíveis, como falha na exclusão de backup, mesmo que o tempo de retenção tenha decorrido.
* O Astra Control não é compatível com políticas de gerenciamento de ciclo de vida dos dados nem com a exclusão manual de objetos nos buckets que você usa com backups imutáveis. Verifique se o back-end de storage não está configurado para gerenciar o ciclo de vida dos snapshots do Astra Control ou dos dados de backup.




== Clones

Um _clone_ é uma cópia exata de um aplicativo, sua configuração e seus volumes de dados persistentes. Você pode criar manualmente um clone no mesmo cluster do Kubernetes ou em outro cluster. Clonar uma aplicação pode ser útil se você precisar mover aplicações e storage de um cluster Kubernetes para outro.
