---
sidebar: sidebar 
permalink: use-acp/acp-snap-restore.html 
keywords: snapshot restore, snapshot, astra control provisioner, TridentActionSnapshotRestore, 
summary: 'O Astra Control Provisioner fornece restauração rápida de volume no local a partir de um snapshot usando o `TridentActionSnapshotRestore` (TASR) CR. Esse CR funciona como uma ação imperativa do Kubernetes e não persiste após a conclusão da operação.' 
---
= Recuperar dados de volume usando um snapshot
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
O Astra Control Provisioner fornece restauração rápida de volume no local a partir de um snapshot usando o `TridentActionSnapshotRestore` (TASR) CR. Esse CR funciona como uma ação imperativa do Kubernetes e não persiste após a conclusão da operação.

O Astra Control Provisioner oferece suporte à restauração de snapshot no `ontap-san` `ontap-san-economy` , , `ontap-nas` `ontap-nas-flexgroup` , , , , `azure-netapp-files` `gcp-cvs`, e `solidfire-san` drivers.

.Antes de começar
Você deve ter um PVC vinculado e instantâneo de volume disponível.

* Verifique se o status do PVC está vinculado.
+
[listing]
----
kubectl get pvc
----
* Verifique se o instantâneo do volume está pronto para ser usado.
+
[listing]
----
kubectl get vs
----


.Passos
. Crie o TASR CR. Este exemplo cria um CR para instantâneo de PVC `pvc1` e volume `pvc1-snapshot` .
+
[listing]
----
cat tasr-pvc1-snapshot.yaml

apiVersion: v1
kind: TridentActionSnapshotRestore
metadata:
  name: this-doesnt-matter
  namespace: trident
spec:
  pvcName: pvc1
  volumeSnapshotName: pvc1-snapshot
----
. Aplique o CR para restaurar a partir do instantâneo. Este exemplo restaura do instantâneo `pvc1`.
+
[listing]
----
kubectl create -f tasr-pvc1-snapshot.yaml

tridentactionsnapshotrestore.trident.netapp.io/this-doesnt-matter created
----


.Resultados
O Astra Control Provisioner restaura os dados do snapshot. Você pode verificar o status de restauração de snapshot.

[listing]
----
kubectl get tasr -o yaml

apiVersion: v1
items:
- apiVersion: trident.netapp.io/v1
  kind: TridentActionSnapshotRestore
  metadata:
    creationTimestamp: "2023-04-14T00:20:33Z"
    generation: 3
    name: this-doesnt-matter
    namespace: trident
    resourceVersion: "3453847"
    uid: <uid>
  spec:
    pvcName: pvc1
    volumeSnapshotName: pvc1-snapshot
  status:
    startTime: "2023-04-14T00:20:34Z"
    completionTime: "2023-04-14T00:20:37Z"
    state: Succeeded
kind: List
metadata:
  resourceVersion: ""
----
[NOTE]
====
* Na maioria dos casos, o Astra Control Provisioner não tentará automaticamente a operação em caso de falha. Terá de efetuar novamente a operação.
* Os usuários do Kubernetes sem acesso de administrador podem ter permissão para que o administrador crie um TASR CR em seu namespace de aplicativo.


====