---
sidebar: sidebar 
permalink: use/log-in.html 
keywords: logging in, log in, sign in, signing in, BlueXP, netapp BlueXP, user account 
summary: O Astra Control Service pode ser acessado por meio de uma interface de usuário baseada em SaaS acessando o astra.NetApp.io. 
---
= Faça login no Astra Control Service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Astra Control Service pode ser acessado por meio de uma interface de usuário baseada em SaaS acessando https://astra.netapp.io[] o .


TIP: Você pode usar o logon único para fazer login usando credenciais de seu diretório corporativo (identidade federada). Para saber mais, vá para o https://cloud.netapp.com/help-center["Centro de Ajuda"^] e selecione *Opções de início de sessão na Cloud Central*.

.Antes de começar
* link:../get-started/register.html["Um ID de usuário do BlueXP "].
* link:../get-started/register.html["Uma nova conta do Astra Control"] ou link:manage-users.html["um convite para uma conta existente"].
* Um navegador da Web compatível.
+
O Astra Control Service suporta versões recentes do Firefox, Safari e Chrome com uma resolução mínima de 1280 x 720.



.Passos
. Abra um navegador da Web e vá para https://astra.netapp.io[].
. Faça login usando suas credenciais NetApp BlueXP .

