---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: Adicione e remova as credenciais do provedor de nuvem da sua conta a qualquer momento. O Astra Control usa essas credenciais para provisionar recursos em seu nome. 
---
= Adicione e remova credenciais
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Adicione e remova as credenciais do provedor de nuvem da sua conta a qualquer momento. O Astra Control usa essas credenciais para descobrir um cluster Kubernetes e as aplicações no cluster e provisionar recursos em seu nome.

Observe que todos os usuários do Astra Control compartilham os mesmos conjuntos de credenciais.



== Adicionar credenciais

A maneira mais comum de adicionar credenciais ao Astra Control é quando você gerencia clusters, mas também pode adicionar credenciais a partir da página da conta. As credenciais estarão disponíveis para você escolher quando você gerenciar clusters adicionais do Kubernetes.

.Antes de começar
ifdef::aws[]

* Para o Amazon Web Services, você deve ter a saída JSON das credenciais para a conta do IAM usada para criar o cluster. link:../get-started/set-up-amazon-web-services.html["Saiba como configurar um usuário do IAM"].


endif::aws[]

ifdef::gcp[]

* Para o GKE, você deve ter o arquivo de chave de conta de serviço para uma conta de serviço que tenha as permissões necessárias. link:../get-started/set-up-google-cloud.html["Saiba como configurar uma conta de serviço"].


endif::gcp[]

ifdef::azure[]

* Para AKS, você deve ter o arquivo JSON que contém a saída da CLI do Azure quando você criou o responsável pelo serviço. link:../get-started/set-up-microsoft-azure-with-anf.html["Saiba como configurar um diretor de serviço"].
+
Você também precisará do ID de assinatura do Azure, se não o tiver adicionado ao arquivo JSON.



endif::azure[]

.Passos
. Selecione *conta > credenciais*.
. Selecione *Adicionar credenciais*.


ifdef::azure[]

. Selecione *Microsoft Azure*.


endif::azure[]

ifdef::gcp[]

. Selecione *Google Cloud Platform*.


endif::gcp[]

ifdef::aws[]

. Selecione *Amazon Web Services*.


endif::aws[]

. Insira um nome para as credenciais que as distingue de outras credenciais no Astra Control.
. Forneça as credenciais necessárias.


ifdef::azure[]

. *Microsoft Azure*: Forneça ao Astra Control detalhes sobre o seu principal de serviço do Azure, carregando um arquivo JSON ou colando o conteúdo desse arquivo JSON da sua área de transferência.
+
O arquivo JSON deve conter a saída da CLI do Azure quando você criou o principal do serviço. Ele também pode incluir seu ID de assinatura para que ele seja adicionado automaticamente ao Astra Control. Caso contrário, você precisa inserir manualmente o ID após fornecer o JSON.



endif::azure[]

ifdef::gcp[]

. *Google Cloud Platform*: Forneça o arquivo de chave da conta de serviço do Google Cloud carregando o arquivo ou colando o conteúdo da área de transferência.


endif::gcp[]

ifdef::aws[]

. *Amazon Web Services*: Forneça as credenciais de usuário do Amazon Web Services IAM ao carregar o arquivo ou colando o conteúdo da área de transferência.


endif::aws[]

. Selecione *Adicionar credenciais*.


.Resultado
As credenciais agora estão disponíveis para seleção quando você adiciona um cluster ao Astra Control.



== Remover credenciais

Remova as credenciais de uma conta a qualquer momento. Só deve remover credenciais após link:unmanage.html["desgerenciar todos os clusters"], a menos que esteja a rodar credenciais (<<Gire as credenciais>>consulte a ).


NOTE: O primeiro conjunto de credenciais que você adiciona ao Astra Control está sempre em uso porque o Astra Control usa as credenciais para autenticar no bucket do backup. É melhor não remover essas credenciais.

.Passos
. Selecione *conta > credenciais*.
. Selecione a lista suspensa na coluna *Estado* para obter as credenciais que deseja remover.
. Selecione *Remover*.
. Digite o nome das credenciais para confirmar a exclusão e selecione *Sim, Remover credenciais*.


.Resultado
O Astra Control remove as credenciais da conta.



== Gire as credenciais

Você pode girar credenciais em sua conta. Se você girar credenciais, gire-as durante uma janela de manutenção quando nenhum backup estiver em andamento (agendado ou sob demanda).

.Passos
. Remova as credenciais existentes seguindo as etapas em <<Remover credenciais>>.
. Adicione as novas credenciais seguindo as etapas em <<Adicionar credenciais>>.
. Atualize todos os buckets para usar as novas credenciais:
+
.. Na navegação à esquerda, selecione *Buckets*.
.. Selecione a lista suspensa na coluna *ações* para o intervalo que você deseja editar.
.. Selecione *Editar*.
.. Na seção *Selecionar credenciais*, escolha as novas credenciais adicionadas ao Astra Control.
.. Selecione *Atualizar*.
.. Repita os passos *b* a *e* para quaisquer baldes restantes no seu sistema.




.Resultado
O Astra Control começa a usar as novas credenciais do fornecedor de nuvem.
